export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILED="LOGIN_FAILED"

export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILED="REGISTER_USER_FAILED"

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS"
export const LOAD_USER_FAILED="LOAD_USER_FAILED"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_FAILED="LOGOUT_FAILED"

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILED="UPDATE_PROFILE_FAILED"
export const UPDATE_PROFILE_RESET="UPDATE_PROFILE_RESET"

export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAILED="UPDATE_PASSWORD_FAILED"
export const UPDATE_PASSWORD_RESET="UPDATE_PROFILE_RESET"

export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILED="FORGOT_PASSWORD_FAILED"

export const NEW_PASSWORD_REQUEST="NEW_PASSWORD_REQUEST"
export const NEW_PASSWORD_SUCCESS="NEW_PASSWORD_SUCCESS"
export const NEW_PASSWORD_FAILED="NEW_PASSWORD_FAILED"

export const ALL_USERS_REQUEST="ALL_USERS_REQUEST"
export const ALL_USERS_SUCCESS="ALL_USERS_SUCCESS"
export const ALL_USERS_FAILED="ALL_USERS_FAILED"


export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILED="UPDATE_USER_FAILED"
export const UPDATE_USER_RESET="UPDATE_USER_RESET"

export const CLEAR_ERRORS="CLEAR_ERRORS" 

